version: '3.4'

services:
  webclient:
    build: https://github.com/Chikseen/menzel-fahrzeugtechnik-website.git#feature/dotnet-be:web-client
    ports:
      - 8080:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.mfzt.rule=Host(`menzel-fahrzeugtechnik.de`,`www.menzel-fahrzeugtechnik.de`)
      - traefik.http.routers.mfzt.entrypoints=https
      - traefik.http.routers.mfzt.tls=true
      - traefik.http.routers.mfzt.middlewares=external-secure,mfzt-redirect
      - traefik.http.middlewares.mfzt-redirect.redirectregex.regex=https://www\.menzel-fahrzeugtechnik\.de
      - traefik.http.middlewares.mfzt-redirect.redirectregex.replacement=https://menzel-fahrzeugtechnik.de
    depends_on:
      - api
    networks:
      - frontend
      - proxy
    volumes:
      - postgres-data:/Files/images
    restart: always

  api:
    build: https://github.com/Chikseen/menzel-fahrzeugtechnik-website.git#feature/dotnet-be:api
    ports:
      - 7080:7080
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      FILE_PATH: ${FILE_PATH}
    labels:
      - traefik.enable=true
      - traefik.http.routers.mfztapi.rule=Host(`api.menzel-fahrzeugtechnik.de`)
      - traefik.http.routers.mfztapi.entrypoints=https
      - traefik.http.routers.mfztapi.tls=true
      - traefik.http.routers.mfzt.middlewares=external-secure,mfzt-redirect
    depends_on:
      - postgres
    networks:
      - frontend
      - backend
      - proxy

  postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
      
volumes:
  postgres-data:

networks:
  backend:
    internal: true
  frontend:
    driver: bridge
  proxy:
    external: true
